services:
  mysqldb:
    build:
      dockerfile: mysql.Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build:
      dockerfile: app.Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.web.resources.staticLocations" : "$SPRING_STATIC_LOCATION",
        "spring.profiles.active" : "prod",
        "toolbox.upload.path" : "$UPLOAD_PATH"
      }'
    stdin_open: true
    tty: true
    volumes:
      - upload:$UPLOAD_PATH

volumes:
  db:
    external: true
    name: 'toolbox-backend_db'
  upload:
    external: true
    name: 'toolbox-backend_upload'
