spring:
  application:
    name: toolbox-backend

  profiles:
    active:
      - 'dev'
server:
  port: 8080


mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

toolbox:
  administrator:
      email: xxx.gmail

